### ISSUE TITLE
error 404: Item Not Found

### ISSUE THREAD

**Issue by scmaxsr** [sonos-web/sonos-web#13]
hi
i installed sonos-web on a raspberry al go well and i get to the website but things work properly
if i go to music library or my sonos it's getting sluggy and later on i get error
404: Item Not Found

i installed from docker and the normal installation but the same error

what doing wrong

sorry for mij bad english
keep up te good work

**Comment by pwt** [comment]
Just to comment on this: I think that @scmaxsr is using my Docker image for the Pi, as referenced in the following issue: https://github.com/pwt/docker-sonos-web-arm/issues/1.

Feel free to request debugging information regarding the Docker packaging.

**Comment by Villarrealized** [comment]
@scmaxsr Do you have an external music library setup for your Sonos system? The Music Library feature pulls from whatever is available on your network via Sonos.

What is the output from your Raspberry Pi when you run `uname -a`?

**Comment by scmaxsr** [comment]
@Villarrealized Thanks for replying

> @scmaxsr Do you have an external music library setup for your Sonos system? The Music Library feature pulls from whatever is available on your network via Sonos.

I use Spotify and TuneIn

> What is the output from your Raspberry Pi when you run uname -a?

The output of `uname -a` = Linux domoticz 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux

**Comment by scmaxsr** [comment]
@Villarrealized
I add a piece of the log file 
`handledPromiseRejectionWarning: StatusCodeError: 500 - "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xml
soap.org/soap/encoding/\"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\"><
errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"                                                                                              
    at new StatusCodeError (/home/pi/.sonos-web/node_modules/request-promise-core/lib/errors.js:32:15)                                                                       
    at Request.plumbing.callback (/home/pi/.sonos-web/node_modules/request-promise-core/lib/plumbing.js:104:33)                                                              
    at Request.RP$callback [as _callback] (/home/pi/.sonos-web/node_modules/request-promise-core/lib/plumbing.js:46:31)                                                      
    at Request.self.callback (/home/pi/.sonos-web/node_modules/request/request.js:185:22)                                                                                    
    at Request.emit (events.js:189:13)                                                                                                                                       
    at Request.<anonymous> (/home/pi/.sonos-web/node_modules/request/request.js:1161:10)                                                                                     
    at Request.emit (events.js:189:13)                                                                                                                                       
    at IncomingMessage.<anonymous> (/home/pi/.sonos-web/node_modules/request/request.js:1083:12)                                                                             
    at Object.onceWrapper (events.js:277:13)                                                                                                                                 
    at IncomingMessage.emit (events.js:194:15)                                                                                                                               
(node:31144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
 rejecting a promise which was not handled with .catch(). (rejection id: 119)                                                                                                
(node:31144) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - "<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xml
soap.org/soap/encoding/\"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\"><
errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"                                                                                              
    at new StatusCodeError (/home/pi/.sonos-web/node_modules/request-promise-core/lib/errors.js:32:15)                                                                       
    at Request.plumbing.callback (/home/pi/.sonos-web/node_modules/request-promise-core/lib/plumbing.js:104:33)                                                              
    at Request.RP$callback [as _callback] (/home/pi/.sonos-web/node_modules/request-promise-core/lib/plumbing.js:46:31)                                                      
    at Request.self.callback (/home/pi/.sonos-web/node_modules/request/request.js:185:22)                                                                                    
    at Request.emit (events.js:189:13)                                                                                                                                       
    at Request.<anonymous> (/home/pi/.sonos-web/node_modules/request/request.js:1161:10)                                                                                     
    at Request.emit (events.js:189:13)                                                                                                                                       
    at IncomingMessage.<anonymous> (/home/pi/.sonos-web/node_modules/request/request.js:1083:12)                                                                             
    at Object.onceWrapper (events.js:277:13)                                                                                                                                 
    at IncomingMessage.emit (events.js:194:15)                                                                                                                               
(node:31144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
 rejecting a promise which was not handled with .catch(). (rejection id: 120)`

**Comment by broth-eu** [comment]
I'm having the same issue in each environment I've tried:
1. Raspberry Pi 4 with Docker
2. locally on my MacBook without Docker

When I navigate to _Music Library_ I'm always getting "404: Item Not Found", independent of the tab I select.

**Comment by gurtfrobe** [comment]
I'm also getting 404s in the following env:
- Linux KDE Neon
- Firefox (also tried Brave)

**Comment by yoogie27** [comment]
Same here. Regardless of where I am, genre, albums, ...
Some work, some don't. It almost looks like it is truncating the IDs for some entries...

**Comment by yoogie27** [comment]
It looks like for every item I click, it fires 2 requests to the backend. When I receive a 404, one of both responses shows no items (empty items). When it works, both requests have items in the response

**Comment by msj-fr** [comment]
I also have the 404 Item not found in the music library. And searching always returns empty.

**Comment by yoogie27** [comment]
<img width="837" alt="Bildschirmfoto 2019-12-22 um 13 11 36" src="https://user-images.githubusercontent.com/6117540/71321642-ebfe8900-24bc-11ea-9aae-f51e74e123b2.png">

**Comment by yoogie27** [comment]
It seems like the issue is when the album name has either a ":" or "/" in the name.
I have tried to replace it with " " in MusicLibrary.js -> _getSearchOptions, but this is probably too easy...
But certainly, all albums containing either / or : are returning 404

**Comment by yoogie27** [comment]
Solution:

In node_modules/sonos/lib/sonos.js, line 120, replace encodeURI with encodeURIComponent

**Comment by Villarrealized** [comment]
> Solution:
> 
> In node_modules/sonos/lib/sonos.js, line 120, replace encodeURI with encodeURIComponent

Cool! Have you made a pull request for this over at node-sonos?

**Comment by yoogie27** [comment]
> > Solution:
> > In node_modules/sonos/lib/sonos.js, line 120, replace encodeURI with encodeURIComponent
> 
> Cool! Have you made a pull request for this over at node-sonos?

I just did

https://github.com/bencevans/node-sonos/pull/453

**Comment by Villarrealized** [comment]
Thanks @yoogie27. I have updated sonos-web to use the latest node-sonos version in v0.9.9.

**Comment by bdsoha** [comment]
~~I am receiving the same issue.
There is also no indication of _Now playing_~~

I seemed to figure out the issue. When no results are returned from the server *"404: not found"* is displayed.
Maybe the message should be more informative, like *"No results"*.
