### ISSUE TITLE
error while connecting 

### ISSUE THREAD

**Issue by thomasdye12** [sonos-web/sonos-web#19]
hope you can help I've just set this up and when i go to the url i get an error as seen below it is running on a mac 
An unexpected error occurred while searching for your Sonos System: {"name":"StatusCodeError","statusCode":500,"message":"500 - \"<s:Envelope xmlns:s=\\\"http://schemas.xmlsoap.org/soap/envelope/\\\" s:encodingStyle=\\\"http://schemas.xmlsoap.org/soap/encoding/\\\"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns=\\\"urn:schemas-upnp-org:control-1-0\\\"><errorCode>501</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>\"","error":"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\"><errorCode>501</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>","options":{},"response":{"statusCode":500},"stack":"StatusCodeError: 500 - \"<s:Envelope xmlns:s=\\\"http://schemas.xmlsoap.org/soap/envelope/\\\" s:encodingStyle=\\\"http://schemas.xmlsoap.org/soap/encoding/\\\"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns=\\\"urn:schemas-upnp-org:control-1-0\\\"><errorCode>501</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>\"\n at new StatusCodeError (/Users/server/.sonos-web/node_modules/request-promise-core/lib/errors.js:32:15)\n at Request.plumbing.callback (/Users/server/.sonos-web/node_modules/request-promise-core/lib/plumbing.js:104:33)\n at Request.RP$callback [as _callback] (/Users/server/.sonos-web/node_modules/request-promise-core/lib/plumbing.js:46:31)\n at Request.self.callback (/Users/server/.sonos-web/node_modules/request/request.js:185:22)\n at Request.emit (events.js:198:13)\n at Request.<anonymous> (/Users/server/.sonos-web/node_modules/request/request.js:1161:10)\n at Request.emit (events.js:198:13)\n at IncomingMessage.<anonymous> (/Users/server/.sonos-web/node_modules/request/request.js:1083:12)\n at Object.onceWrapper (events.js:286:20)\n at IncomingMessage.emit (events.js:203:15)"}

**Comment by Villarrealized** [comment]
Is your mac connected to the same network as your Sonos system?

**Comment by thomasdye12** [comment]
sorry didn't see your reply 

yes the Mac is connected to the correct wifi because if you disconnected it you don't get an error you just get cannot be found

**Comment by Villarrealized** [comment]
Can you try uninstalling and reinstalling and see what the results are?
