### ISSUE TITLE
install fails on RPi2B w/DietPi

### ISSUE THREAD

**Issue by vMarkus** [sonos-web/sonos-web#7]
```
npm install -g sonos-web-cli
(node:3158) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN optional dep failed, continuing fsevents@1.2.7
```
shows as warning

```
/usr/local/bin/sonos-web -> /usr/local/lib/node_modules/sonos-web-cli/index.js
sonos-web-cli@1.3.0 /usr/local/lib/node_modules/sonos-web-cli
├── commander@2.19.0
├── ip@1.1.5
├── colors@1.3.3
├── fs-extra@7.0.1 (universalify@0.1.2, jsonfile@4.0.0, graceful-fs@4.1.15)
├── ora@3.1.0 (log-symbols@2.2.0, cli-spinners@1.3.1, strip-ansi@5.0.0, wcwidth@1.0.1, cli-cursor@2.1.0, chalk@2.4.2)
├── download-git-repo@1.1.0 (git-clone@0.1.0, rimraf@2.6.3, download@5.0.3)
├── shelljs@0.8.3 (interpret@1.2.0, glob@7.1.3, rechoir@0.6.2)
└── forever@0.15.3 (object-assign@3.0.0, path-is-absolute@1.0.1, colors@0.6.2, clone@1.0.4, timespan@2.3.0, optimist@0.6.1, nssocket@0.5.3, cliff@0.1.10, prettyjson@1.2.1, winston@0.8.3, shush@1.0.0, utile@0.2.1, nconf@0.6.9, flatiron@0.4.3, forever-monitor@1.7.1)
```
follows, looks ok?

next to install sonos-web
```
~# sonos-web install
Installing Sonos Web
✔ downloading installation files
✖ installing front-end dependencies
error installation failed...check /root/.sonos-web/install.log for more details
```
Running on DietPi on a RPi2B, install.log file is zero bytes.

Any hints welcome.

**Comment by Villarrealized** [comment]
My guess is that some of the [front-end dependencies](https://github.com/Villarrealized/sonos-web/blob/master/client/package.json) are incompatible with the RPi2B? 

You could try installing them manually to get a better idea of where it's failing:

```bash
cd ~/.sonos-web
cd client
npm install
```

**Comment by Villarrealized** [comment]
I’m not too familiar with DietPi, but might be something missing that is available on Raspbian Lite. Haven’t tried running it on that setup.

Best bet is to try the above and see where that gets us.

**Comment by vMarkus** [comment]
just tried as recommended... 

```
~/.sonos-web/client# npm install
(node:12133) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /root/.sonos-web/client
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/.sonos-web/client/npm-debug.log
npm ERR! not ok code 0
```

from npm-debug.log
```
758 silly addNameRange     '5.2.1' ] ]
759 verbose addNamed [ 'eslint-plugin-vue', '5.2.1' ]
760 verbose addNamed [ '5.2.1', '5.2.1' ]
761 silly lockFile 455fc02f-eslint-plugin-vue-5-2-1 eslint-plugin-vue@5.2.1
762 verbose lock eslint-plugin-vue@5.2.1 /root/.npm/455fc02f-eslint-plugin-vue-5-2-1.lock
763 error Error: Method Not Allowed
763 error     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
763 error     at /usr/share/npm/lib/cache/add-named.js:203:12
763 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
763 error     at FSReqWrap.oncomplete (fs.js:135:15)
764 error If you need help, you may report this *entire* log,
764 error including the npm and node versions, at:
764 error     <http://github.com/npm/npm/issues>
765 error System Linux 4.14.79+
766 error command "/usr/bin/node" "/usr/bin/npm" "install"
767 error cwd /root/.sonos-web/client
768 error node -v v8.11.1
769 error npm -v 1.4.21
770 error code E405
771 verbose exit [ 1, true ]
```

Found similar errors on add-named.js on [https://forum.magicmirror.builders/post/49472](https://forum.magicmirror.builders/post/49472) 
> for the last couple months Node.js and npm are currently BROKEN on RaspberryPi.

installed node-v9.11.2-linux-armv6l.tar.xz manually as discribed [here](https://www.instructables.com/id/Install-Nodejs-and-Npm-on-Raspberry-Pi/) - had to logout and login w/ssh to make sure node-v and npm -v come back with latest version 

after that 
`npm install`
went through

`sonos-web install`
went through as well

Access to webpage is possible, but hangs at loading. Will leave this open and dig a little deeper. 

Docker deployment on a Synology using [Node](https://hub.docker.com/_/node/) finds my Sonos speakers on the same subnet as is my RPi - so it shouldn't be a networking issue.
